language: cpp

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=serial.MM} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=serial.QMMM} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=serial.sander.SEBOMD} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=fast} # AmberTools/test
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_IN_AMBERHOME=True TEST_TASK=python} # Ambertools/test + amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 USE_AMBER_PREFIX=True TEST_TASK=fast} # Ambertools/test
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=mmpbsa} # Ambertools/test
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=rism} # Ambertools/test
     - { os: linux, env: PYTHON_VERSION=2.7 AMBER_INSTALL_MPI=True}
     - { os: linux, env: PYTHON_VERSION=2.7 USE_WITH_PYTHON=True TEST_TASK=python}
     - { os: linux, env: PYTHON_VERSION=3.5 TEST_TASK=python} 

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - unzip
    - csh
    - flex
    - patch
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
    - xutils-dev
    - clang

install:
    - source devtools/ci/load_functions.sh
    - download_ambertools
    - install_ambertools_travis

script:
    - run_tests

after_success:
    - echo "Congrats. Happy computing"

notifications:
  email:
    recipients:
      - nhai.qn@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  
