language: cpp

matrix:
  include:
     - { os: osx, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True TEST_TASK=fast COMPILER=clang }

sudo: true

addons:
  apt:
    packages:
    - gfortran
    - unzip
    - csh
    - flex
    - patch
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
    - xutils-dev
    - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw;
      sudo sh devtools/ci/install_gfortran.sh;
    fi

install:
    - source devtools/ci/load_functions.sh
    - download_ambertools
    - install_ambertools_travis

script:
    - run_tests

after_success:
    - echo "Congrats. Happy computing"

notifications:
  email:
    recipients:
      - nhai.qn@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  
